### ISSUE TITLE
turn “HTML String / text file” into HTML/webpage with all items from a selected category.

### ISSUE THREAD

**Issue by abparker** [codeforsanjose/council-catalog#3]

**Comment by JMStudiosJoe** [comment]
Has someone specified what kind of frontend like react or angular or just raw js and html @abparker? Also looks like there are some html files made for searching or are those just templates that need to be connected to a frontend? Can you provide more detail on the search directory?

**Comment by 3vivekb** [comment]
I think scraping and designing and setting up some database structure and queries comes first.

If somebody wants to make a design and do frontend, draw something out then do something super simple like bootstrap that would be good.

**Comment by 3vivekb** [comment]
Actually i'm not sure what this issue is about...
